/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.onner.form;

import com.onner.async.FoodProcess;
import com.onner.async.SnakeProcess;
import com.onner.async.SoundProcess;
import com.onner.component.SoundPlayer;
import com.onner.global.GlobalVariables;

import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.*;

/**
 * @author lionos
 */
public class Space extends javax.swing.JFrame {

    /**
     * Creates new form Space
     */
    private SoundProcess soundProcess;

    public Space() {
        initComponents();
        initGeneral();
    }

    private void initGeneral() {
        this.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLayout(null);
        //this.setResizable(false);
        this.windowsnake.setLayout(null);
        this.board.setLayout(null);
        this.space.setLayout(null);

        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                adjustSpacePanelSize();
            }
        });

        SoundPlayer soundPlayer = new SoundPlayer();
        soundProcess = new SoundProcess(soundPlayer);

        new Thread( new FoodProcess( this.space, this.food, this.time)).start();
        new Thread( new SnakeProcess( this.space, this.food, soundProcess)).start();
        new Thread( soundProcess ).start();

        //this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.setLocation(1000,500);
    }
    
    private void adjustSpacePanelSize() {
        windowsnake.setSize(getWidth(), getHeight());
        space.setSize(windowsnake.getWidth() - 100, windowsnake.getHeight() - 150);
        space.setLocation(50, 50);
        board.setSize(windowsnake.getWidth() - 100, 50);
        board.setLocation(50, 0);
        int xPositionLabel = (board.getWidth() / 2) - 50;
        int xPositionScore = (board.getWidth() / 2) + 50;
        jlabel_score.setLocation( xPositionLabel , WIDTH + 15);
        score.setLocation( xPositionScore , WIDTH + 15);
        icon1.setLocation(board.getWidth() - 50, WIDTH );
        jlabel_losses.setLocation(board.getWidth() - 200,WIDTH + 15);
        losses.setLocation(board.getWidth() - 100,WIDTH + 15);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowsnake = new javax.swing.JPanel();
        board = new javax.swing.JPanel();
        jlabel_score = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        jlabel_losses = new javax.swing.JLabel();
        losses = new javax.swing.JLabel();
        jlabel_level = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        space = new javax.swing.JPanel();
        food = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jToggleButtonStop = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("snake");
        setBackground(new java.awt.Color(51, 153, 0));
        setName("space"); // NOI18N

        windowsnake.setBackground(new java.awt.Color(49, 64, 23));
        windowsnake.setPreferredSize(new java.awt.Dimension(1000, 600));

        board.setBackground(new java.awt.Color(49, 64, 23));
        board.setPreferredSize(new java.awt.Dimension(900, 50));

        jlabel_score.setBackground(new java.awt.Color(204, 204, 204));
        jlabel_score.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jlabel_score.setForeground(new java.awt.Color(204, 204, 204));
        jlabel_score.setText("SCORE :");

        score.setBackground(new java.awt.Color(204, 204, 204));
        score.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        score.setForeground(new java.awt.Color(204, 204, 204));
        score.setText("00");

        jlabel_losses.setBackground(new java.awt.Color(204, 204, 204));
        jlabel_losses.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jlabel_losses.setForeground(new java.awt.Color(204, 204, 204));
        jlabel_losses.setText("LOSSES :");

        losses.setBackground(new java.awt.Color(204, 204, 204));
        losses.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        losses.setForeground(new java.awt.Color(204, 204, 204));
        losses.setText("00");

        jlabel_level.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jlabel_level.setForeground(new java.awt.Color(204, 204, 204));
        jlabel_level.setText("LEVEL :");

        level.setBackground(new java.awt.Color(204, 204, 204));
        level.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        level.setForeground(new java.awt.Color(204, 204, 204));
        level.setText("0");

        icon.setIcon(new javax.swing.ImageIcon("/run/media/lionos/Lion/2024-I/Parallel-Programming/unit-ii/Project/snake/src/main/java/com/onner/resources/snake_logo50x50.png")); // NOI18N

        icon1.setIcon(new javax.swing.ImageIcon("/run/media/lionos/Lion/2024-I/Parallel-Programming/unit-ii/Project/snake/src/main/java/com/onner/resources/snake_logo50x50.png")); // NOI18N

        javax.swing.GroupLayout boardLayout = new javax.swing.GroupLayout(board);
        board.setLayout(boardLayout);
        boardLayout.setHorizontalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boardLayout.createSequentialGroup()
                .addComponent(icon)
                .addGap(18, 18, 18)
                .addComponent(jlabel_level)
                .addGap(13, 13, 13)
                .addComponent(level)
                .addGap(214, 214, 214)
                .addComponent(jlabel_score)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(score)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jlabel_losses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(losses)
                .addGap(24, 24, 24)
                .addComponent(icon1))
        );
        boardLayout.setVerticalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlabel_level)
                .addGroup(boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(level)
                    .addComponent(score)
                    .addComponent(jlabel_score)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlabel_losses)
                .addComponent(losses))
            .addComponent(icon, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        space.setBackground(new java.awt.Color(255, 200, 55));
        space.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 131, 5), 3));
        space.setPreferredSize(new java.awt.Dimension(900, 500));
        space.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                spaceMouseMoved(evt);
            }
        });

        food.setIcon(new javax.swing.ImageIcon("/run/media/lionos/Lion/2024-I/Parallel-Programming/unit-ii/Project/snake/src/main/java/com/onner/resources/apple.gif")); // NOI18N

        javax.swing.GroupLayout spaceLayout = new javax.swing.GroupLayout(space);
        space.setLayout(spaceLayout);
        spaceLayout.setHorizontalGroup(
            spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spaceLayout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(food)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        spaceLayout.setVerticalGroup(
            spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spaceLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(food)
                .addGap(222, 222, 222))
        );

        time.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        time.setForeground(new java.awt.Color(204, 204, 204));
        time.setText("0");

        jToggleButtonStop.setText("->");
        jToggleButtonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonStopMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout windowsnakeLayout = new javax.swing.GroupLayout(windowsnake);
        windowsnake.setLayout(windowsnakeLayout);
        windowsnakeLayout.setHorizontalGroup(
            windowsnakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowsnakeLayout.createSequentialGroup()
                .addGroup(windowsnakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(windowsnakeLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(time))
                    .addComponent(jToggleButtonStop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(windowsnakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(board, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(space, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        windowsnakeLayout.setVerticalGroup(
            windowsnakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowsnakeLayout.createSequentialGroup()
                .addGroup(windowsnakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(windowsnakeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButtonStop))
                .addGroup(windowsnakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(space, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowsnake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowsnake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonStopMouseClicked
        // TODO add your handling code here:
        GlobalVariables.collision = true;
    }//GEN-LAST:event_jToggleButtonStopMouseClicked

    private void spaceMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spaceMouseMoved
        // TODO add your handling code here:
        GlobalVariables.mousePositionX = evt.getX();
        GlobalVariables.mousePositionY = evt.getY();
    }//GEN-LAST:event_spaceMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Space.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Space().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel board;
    private javax.swing.JLabel food;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JToggleButton jToggleButtonStop;
    private javax.swing.JLabel jlabel_level;
    private javax.swing.JLabel jlabel_losses;
    private javax.swing.JLabel jlabel_score;
    public static javax.swing.JLabel level;
    public static javax.swing.JLabel losses;
    public static javax.swing.JLabel score;
    private javax.swing.JPanel space;
    private javax.swing.JLabel time;
    private javax.swing.JPanel windowsnake;
    // End of variables declaration//GEN-END:variables
}
